wayfair-incubator/telefonistka

- internal/pkg/promotion/promotion.go
- templates/drift-pr-comment.gotmpl
> Formatting changes to drift msg

- README.md
- docs/installation.md
- docs/observability.md
> refactor docs

- docs/installation.md
- internal/pkg/configuration/config.go
- internal/pkg/configuration/config_test.go
- internal/pkg/configuration/tests/testConfigurationParsing.yaml
- internal/pkg/promotion/promotion.go
- internal/pkg/promotion/promotion_test.go
closes: https://github.com/wayfair-incubator/telefonistka/issues/15
Refactor the targetPaths struct to make it more intuitive.
The Array of array was very unintuitive
> Change "targetPaths" configuration scheme

- README.md
- docs/installation.md
- docs/modeling_environments_in_gitops_repo.md
- docs/observability.md
- internal/pkg/prometheus/prometheus.go
Address @borischerkasky feedback on docs
Reformat merics to table.
Refactor some of the "modeling" part to a seperate file.
Fix multiple phrasing issues.
> Update and refactor docs baseds on user feedback

- README.md
> Reading over README

- README.md
- docs/installation.md
> Typos readme

- README.md
> Add Link ArgoCon session in README.md

- .github/workflows/docker-publish.yml
Migrating to a more reasonably named DockerHub org:  wayfaiross/telefonistka
> Migrate to  Wayfair's OSS dockerhub org

- internal/pkg/githubapi/github.go
Fix some regression added by the file  deletion [fix](https://github.com/wayfair-incubator/telefonistka/pull/67)
> Fix regression from the deletion fix

- internal/pkg/githubapi/clients.go
Another try at the  graphql/Rest URL mess(I really need some integration/ e2e tests)
> Another try at the graphql/Rest URL game

- .github/workflows/docker-publish-on-comment.yml
Currently I release images to test them outside my machine, not great.
Testing a CI change that should allow me to publish unreleased images, on demand.
> Test a comment triggered build

- .github/workflows/docker-publish-on-comment.yml
> Allow PR to comment/set status

- .github/workflows/docker-publish-on-comment.yml
> Address some build config

- .github/workflows/docker-publish-on-comment.yml
Comment contianer image tag on PR comment on "publish request"
> Display tags on publish comment

- .github/workflows/docker-publish-on-comment.yml
Images published from PRs (non-main branch) would get the the main branch GIT SHA/ref in their tags, this tries to address it
- [] Bug Fix
CI change
> Fix wrong tags on PR built images

- templates/drift-pr-comment.gotmpl
> Fix typo: promtion -> promotion

- .github/workflows/docker-publish-on-comment.yml
- .github/workflows/docker-publish.yml
> Disable Publishing of images to DockerHub until token issue is addressed

- .github/workflows/docker-publish-on-comment.yml
- .github/workflows/docker-publish.yml
> Make image publish more flexible by moving image name and registery to "repo settings"

- .github/workflows/docker-publish-on-comment.yml
- .github/workflows/docker-publish.yml
- .github/workflows/lint.yml
- .github/workflows/stale.yml
People with forks should be able to publish and test their changes independently of "upstream" telefonistka release cycle.
This PR should help
> Better support publishing container images from forked repos

- internal/pkg/githubapi/promotion.go
- internal/pkg/githubapi/promotion_test.go
Fixes: https://github.com/wayfair-incubator/telefonistka/issues/137
- Support pagination for "List files in PR" API call
- Add some comment to the test
> Add pagination to "List files in PR" api call

- docs/installation.md
> Document APPROVER_GITHUB_APP_ID and APPROVER_GITHUB_APP_PRIVATE_KEY_PATH env vars
